# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host:     <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: somos_app_development

test:
  <<: *default
  database: somos_app_test

production:
  primary:
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>
  cable:
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>