# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host:     localhost

development:
  <<: *default
  database: somos_app_development

test:
  <<: *default
  database: somos_app_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>